import React, { useState, useMemo, useEffect } from 'react';
import { 
  Calendar, 
  ChevronLeft, 
  MessageSquare, 
  Send, 
  Settings, 
  LayoutDashboard,
  Box,
  Hash,
  Ruler,
  Layers,
  Activity,
  User,
  Clock
} from 'lucide-react';
import { motion } from 'motion/react';
import { ProductionItem, ProductionRecord } from '../types';
import { cn } from '../lib/utils';
import { db } from '../lib/firebase';
import { collection, query, where, getDocs, onSnapshot } from 'firebase/firestore';
import { format, parseISO, startOfDay } from 'date-fns';

interface WhatsAppReportProps {
  onBack: () => void;
  user: any;
  key?: string;
}

interface MachineDailyReport {
  machine: ProductionItem;
  dayShift?: ProductionRecord;
  nightShift?: ProductionRecord;
}

export function WhatsAppReport({ onBack, user }: WhatsAppReportProps) {
  const [selectedDate, setSelectedDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  const [loading, setLoading] = useState(false);
  const [machines, setMachines] = useState<ProductionItem[]>([]);
  const [reports, setReports] = useState<MachineDailyReport[]>([]);

  // Fetch all machines first
  useEffect(() => {
    if (!user) return;
    const q = query(collection(db, 'machines'), where('ownerId', '==', user.uid));
    const unsub = onSnapshot(q, (snapshot) => {
      const items: ProductionItem[] = [];
      snapshot.forEach(doc => items.push({ ...doc.data() as ProductionItem, id: doc.id }));
      setMachines(items);
    });
    return unsub;
  }, [user]);

  // Fetch reports whenever date or machines change
  useEffect(() => {
    const fetchReports = async () => {
      if (machines.length === 0) return;
      setLoading(true);
      
      const newReports: MachineDailyReport[] = [];

      for (const machine of machines) {
        const logsRef = collection(db, 'machines', machine.id, 'logs');
        const q = query(
          logsRef, 
          where('date', '==', selectedDate),
          where('userId', '==', user.uid)
        );
        const logSnap = await getDocs(q);
        
        let dayShift: ProductionRecord | undefined;
        let nightShift: ProductionRecord | undefined;

        logSnap.forEach(doc => {
          const data = doc.data() as ProductionRecord;
          if (data.shift === 'DAY') dayShift = data;
          if (data.shift === 'NIGHT') nightShift = data;
        });

        newReports.push({
          machine,
          dayShift,
          nightShift
        });
      }

      setReports(newReports);
      setLoading(false);
    };

    fetchReports();
  }, [machines, selectedDate]);

  const generateWhatsAppMessage = () => {
    const dateFormatted = format(parseISO(selectedDate), 'EEEE, MMM do, yyyy');
    const separator = "🎰🎰🎰🎰🎰🎰🎰🎰🎰🎰🎰";
    let message = `*Production Report -*\n📅${dateFormatted}\n${separator}\n`;

    reports.forEach((report) => {
      message += `*Machine: ${report.machine.name} (${report.machine.category})*\n`;
      message += `DAY SHIFT       NIGHT SHIFT\n`;
      message += `Karigar ⬇️       Karigar ⬇️\n`;
      
      const dayOp = report.dayShift?.operatorName || "No Entry";
      const nightOp = report.nightShift?.operatorName || "No Entry";
      // padding for visual column appearance
      const dayOpPadding = dayOp.padEnd(18, ' ');
      message += `  ${dayOpPadding}${nightOp}\n`;
      
      const dayFrame = report.dayShift?.frame || '-';
      const nightFrame = report.nightShift?.frame || '-';
      const dayFrameText = `Frame: ${dayFrame}`.padEnd(18, ' ');
      message += `  ${dayFrameText}Frame: ${nightFrame}\n`;
      
      message += `Total Tich        Total Tich\n`;
      const dayStitch = report.dayShift?.totalStitches.toLocaleString() || "0";
      const nightStitch = report.nightShift?.totalStitches.toLocaleString() || "0";
      const dayStitchPadding = dayStitch.padEnd(18, ' ');
      message += `  ${dayStitchPadding}${nightStitch}\n`;
      
      message += `${separator}\n`;
    });

    message += `\n_Generated by PT Production Tracker_`;
    return encodeURIComponent(message);
  };

  const handleShare = () => {
    const waUrl = `https://wa.me/?text=${generateWhatsAppMessage()}`;
    window.open(waUrl, '_blank');
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      className="space-y-8 pb-32"
    >
      {/* Header Panel */}
      <div className="bg-[#fcfaf8] rounded-[3.5rem] p-10 flex flex-col sm:flex-row items-center justify-between gap-8 border border-white/60 shadow-soft overflow-hidden relative">
        <div className="absolute top-0 right-0 p-16 bg-[#ffafcc]/5 blur-[100px] rounded-full translate-x-12 -translate-y-12" />
        
        <div className="flex items-center gap-6 relative z-10 w-full sm:w-auto">
          <button 
            onClick={onBack}
            className="p-5 sm:p-6 pill-button rounded-[2rem] transition-all text-slate-800 active:scale-90"
          >
            <ChevronLeft className="w-8 h-8" />
          </button>
          <div>
            <h2 className="text-3xl sm:text-4xl font-black text-slate-800 font-display tracking-tight leading-none uppercase italic">Report Node</h2>
            <div className="flex items-center gap-4 mt-4">
              <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse shadow-[0_0_10px_2px_rgba(52,211,153,0.3)]" />
              <p className="text-[11px] font-black text-slate-400 uppercase tracking-[0.4em]">Transmission Ready</p>
            </div>
          </div>
        </div>

        <div className="relative group w-full sm:w-auto">
          <div className="absolute left-5 top-1/2 -translate-y-1/2 p-3 bg-slate-800 text-white rounded-2xl shadow-soft z-10">
            <Calendar className="w-5 h-5" />
          </div>
          <input 
            type="date" 
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="w-full sm:w-auto pl-20 pr-10 py-6 form-input-premium bg-white cursor-pointer"
          />
        </div>
      </div>

      {/* Loading & Content Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
        {loading ? (
          [1, 2, 3, 4, 5, 6].map(i => (
            <div key={i} className="h-80 bg-white rounded-[3.5rem] border border-white/60 animate-pulse shadow-soft" />
          ))
        ) : (
          reports.map((report) => (
            <motion.div 
              key={report.machine.id}
              whileHover={{ y: -10 }}
              className="soft-card p-10 space-y-8 border border-white transition-all duration-500 group relative"
            >
              <div className="flex items-center gap-6 border-b border-slate-50 pb-8">
                <div className="w-14 h-14 bg-slate-800 text-white rounded-[1.8rem] flex items-center justify-center shadow-soft-sm rotate-6 group-hover:rotate-0 transition-transform duration-500">
                  <Box className="w-7 h-7" />
                </div>
                <div>
                  <h3 className="text-xl font-black text-slate-800 uppercase font-display leading-none tracking-tight">{report.machine.name}</h3>
                  <div className="flex items-center gap-3 mt-3">
                    <span className="text-[10px] font-black text-blue-500 uppercase tracking-[0.4em] bg-[#bde0fe]/30 px-4 py-1.5 rounded-full">
                      {report.machine.category}
                    </span>
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                <ShiftSummary 
                  shift="DAY" 
                  log={report.dayShift} 
                  icon={Clock} 
                  color="amber"
                />
                <ShiftSummary 
                  shift="NIGHT" 
                  log={report.nightShift} 
                  icon={Clock} 
                  color="slate"
                />
              </div>
            </motion.div>
          ))
        )}
      </div>

      <div className="fixed bottom-12 left-1/2 -translate-x-1/2 z-50 px-8 w-full max-w-2xl">
        <button 
          onClick={handleShare}
          disabled={loading || reports.length === 0}
          className="group relative w-full py-6 sm:py-8 pill-button-success rounded-[3.5rem] font-black text-[12px] sm:text-sm uppercase tracking-[0.5em] flex items-center justify-center gap-6 transition-all disabled:opacity-50 disabled:grayscale overflow-hidden border border-white/60 active:scale-[0.98]"
        >
          <div className="relative z-10 flex items-center gap-4">
            <Send className="w-6 h-6 sm:w-8 sm:h-8 group-hover:translate-x-1 transition-transform" />
            <span>Broadcast Transmission</span>
          </div>
        </button>
      </div>

      {!loading && reports.length === 0 && (
        <div className="py-40 flex flex-col items-center justify-center text-center space-y-6 soft-card border border-white mt-12 max-w-2xl mx-auto">
          <div className="p-8 soft-inset bg-white rounded-[2.5rem]">
            <Box className="w-16 h-16 text-slate-300" />
          </div>
          <div>
            <h3 className="text-xl font-black text-slate-900 font-display uppercase tracking-tight">Empty Registry</h3>
            <p className="text-[10px] text-slate-400 uppercase tracking-[0.3em] font-black mt-3">Please initialize assets to generate telemetry records</p>
          </div>
        </div>
      )}
    </motion.div>
  );
}

function ShiftSummary({ shift, log, icon: Icon, color }: { 
  shift: 'DAY' | 'NIGHT', 
  log?: ProductionRecord, 
  icon: any, 
  color: string 
}) {
  if (!log) {
    return (
      <div className="bg-slate-50/50 rounded-[2rem] p-5 border-2 border-dashed border-slate-100 flex items-center justify-between opacity-50 grayscale transition-all">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-slate-100 rounded-xl">
            <Icon className="w-4 h-4 text-slate-400" />
          </div>
          <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{shift} SHIFT</span>
        </div>
        <span className="text-[9px] font-black text-slate-300 uppercase tracking-[0.2em] border border-slate-200 px-3 py-1 rounded-full">Null Log</span>
      </div>
    );
  }

  const isDay = shift === 'DAY';

  return (
    <div className={cn(
      "rounded-[2rem] p-5 border-2 transition-all group/shift",
      isDay ? "bg-amber-50/20 border-amber-50 shadow-sm" : "bg-slate-50 border-slate-100"
    )}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className={cn(
            "p-2 rounded-xl shadow-sm",
            isDay ? "bg-amber-400 text-white" : "bg-slate-900 text-white"
          )}>
            <Icon className="w-4 h-4" />
          </div>
          <span className={cn("text-[10px] font-black uppercase tracking-[0.2em]", isDay ? "text-amber-800" : "text-slate-900")}>
            {shift}
          </span>
        </div>
        <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-xl border border-slate-100 shadow-sm">
          <User className="w-3 h-3 text-indigo-400" />
          <span className="text-[10px] font-black uppercase text-slate-700 font-display">{log.operatorName}</span>
        </div>
      </div>
      
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <p className="text-[10px] font-black text-slate-900 uppercase truncate max-w-[150px] italic">{log.designName}</p>
          <div className="h-px flex-1 mx-4 bg-slate-100" />
        </div>
        
        <div className="flex items-center gap-4">
          <div className="bg-white/80 p-2.5 rounded-2xl flex items-center gap-2 shadow-sm border border-slate-50 flex-1">
            <Activity className="w-3 h-3 text-indigo-500" />
            <span className="text-[11px] font-black text-slate-900">{log.totalStitches.toLocaleString()}</span>
          </div>
          <div className="bg-white/80 p-2.5 rounded-2xl flex items-center gap-2 shadow-sm border border-slate-50 flex-1">
            <Ruler className="w-3 h-3 text-emerald-500" />
            <span className="text-[11px] font-black text-slate-900">{log.totalMeters}m</span>
          </div>
        </div>
      </div>
    </div>
  );
}
