import React, { useState, useMemo, useEffect } from 'react';
import { 
  Calendar, 
  ChevronLeft, 
  MessageSquare, 
  Send, 
  Settings, 
  LayoutDashboard,
  Box,
  Hash,
  Ruler,
  Layers,
  Activity,
  User,
  Clock
} from 'lucide-react';
import { motion } from 'motion/react';
import { ProductionItem, ProductionRecord } from '../types';
import { cn } from '../lib/utils';
import { db } from '../lib/firebase';
import { collection, query, where, getDocs, onSnapshot } from 'firebase/firestore';
import { format, parseISO, startOfDay } from 'date-fns';

interface WhatsAppReportProps {
  onBack: () => void;
  user: any;
  key?: string;
}

interface MachineDailyReport {
  machine: ProductionItem;
  dayShift?: ProductionRecord;
  nightShift?: ProductionRecord;
}

export function WhatsAppReport({ onBack, user }: WhatsAppReportProps) {
  const [selectedDate, setSelectedDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  const [loading, setLoading] = useState(false);
  const [machines, setMachines] = useState<ProductionItem[]>([]);
  const [reports, setReports] = useState<MachineDailyReport[]>([]);

  // Fetch all machines first
  useEffect(() => {
    if (!user) return;
    const q = query(collection(db, 'machines'), where('ownerId', '==', user.uid));
    const unsub = onSnapshot(q, (snapshot) => {
      const items: ProductionItem[] = [];
      snapshot.forEach(doc => items.push({ ...doc.data() as ProductionItem, id: doc.id }));
      setMachines(items);
    });
    return unsub;
  }, [user]);

  // Fetch reports whenever date or machines change
  useEffect(() => {
    const fetchReports = async () => {
      if (machines.length === 0) return;
      setLoading(true);
      
      const newReports: MachineDailyReport[] = [];

      for (const machine of machines) {
        const logsRef = collection(db, 'machines', machine.id, 'logs');
        const q = query(
          logsRef, 
          where('date', '==', selectedDate),
          where('userId', '==', user.uid)
        );
        const logSnap = await getDocs(q);
        
        let dayShift: ProductionRecord | undefined;
        let nightShift: ProductionRecord | undefined;

        logSnap.forEach(doc => {
          const data = doc.data() as ProductionRecord;
          if (data.shift === 'DAY') dayShift = data;
          if (data.shift === 'NIGHT') nightShift = data;
        });

        newReports.push({
          machine,
          dayShift,
          nightShift
        });
      }

      setReports(newReports);
      setLoading(false);
    };

    fetchReports();
  }, [machines, selectedDate]);

  const generateWhatsAppMessage = () => {
    const dateFormatted = format(parseISO(selectedDate), 'EEEE, MMM do, yyyy');
    const separator = "🎰🎰🎰🎰🎰🎰🎰🎰🎰🎰🎰";
    let message = `*Production Report -*\n📅${dateFormatted}\n${separator}\n`;

    reports.forEach((report) => {
      message += `*Machine: ${report.machine.name} (${report.machine.category})*\n`;
      message += `DAY SHIFT       NIGHT SHIFT\n`;
      message += `Karigar ⬇️       Karigar ⬇️\n`;
      
      const dayOp = report.dayShift?.operatorName || "No Entry";
      const nightOp = report.nightShift?.operatorName || "No Entry";
      // padding for visual column appearance
      const dayOpPadding = dayOp.padEnd(18, ' ');
      message += `  ${dayOpPadding}${nightOp}\n`;
      
      const dayFrame = report.dayShift?.frame || '-';
      const nightFrame = report.nightShift?.frame || '-';
      const dayFrameText = `Frame: ${dayFrame}`.padEnd(18, ' ');
      message += `  ${dayFrameText}Frame: ${nightFrame}\n`;
      
      message += `Total Tich        Total Tich\n`;
      const dayStitch = report.dayShift?.totalStitches.toLocaleString() || "0";
      const nightStitch = report.nightShift?.totalStitches.toLocaleString() || "0";
      const dayStitchPadding = dayStitch.padEnd(18, ' ');
      message += `  ${dayStitchPadding}${nightStitch}\n`;
      
      message += `${separator}\n`;
    });

    message += `\n_Generated by PT Production Tracker_`;
    return encodeURIComponent(message);
  };

  const handleShare = () => {
    const waUrl = `https://wa.me/?text=${generateWhatsAppMessage()}`;
    window.open(waUrl, '_blank');
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6 pb-20"
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button 
            onClick={onBack}
            className="p-2 hover:bg-slate-100 rounded-xl transition-colors"
          >
            <ChevronLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">WhatsApp Reports</h2>
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-0.5">Share Daily Production</p>
          </div>
        </div>
        <div className="relative">
          <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input 
            type="date" 
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="pl-9 pr-4 py-2.5 bg-white border border-slate-200 rounded-xl text-sm font-bold text-slate-700 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all shadow-sm outline-none"
          />
        </div>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-40 bg-white border border-slate-100 rounded-3xl animate-pulse" />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reports.map((report) => (
            <div 
              key={report.machine.id}
              className="bg-white border border-slate-100 rounded-[2rem] p-5 shadow-sm space-y-4 hover:shadow-md transition-shadow"
            >
              <div className="flex items-center gap-3 border-b border-slate-50 pb-3">
                <div className="w-10 h-10 bg-slate-900 text-white rounded-xl flex items-center justify-center">
                  <Box className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-black text-slate-800 uppercase leading-none">{report.machine.name}</h3>
                  <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mt-1">{report.machine.category}</p>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-3">
                <ShiftSummary 
                  shift="DAY" 
                  log={report.dayShift} 
                  icon={Clock} 
                  color="amber"
                />
                <ShiftSummary 
                  shift="NIGHT" 
                  log={report.nightShift} 
                  icon={Clock} 
                  color="slate"
                />
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Floating Action Button */}
      <div className="fixed bottom-8 left-1/2 -translate-x-1/2 z-50 px-4 w-full max-w-md">
        <button 
          onClick={handleShare}
          disabled={loading || reports.length === 0}
          className="w-full py-4 bg-emerald-600 text-white rounded-2xl font-black text-sm uppercase tracking-[0.2em] flex items-center justify-center gap-3 shadow-[0_10px_20px_-10px_rgba(16,185,129,0.5)] hover:bg-emerald-500 transition-all active:scale-95 disabled:opacity-50 disabled:grayscale"
        >
          <MessageSquare className="w-5 h-5" />
          <span>WhatsApp Production Report</span>
        </button>
      </div>

      {!loading && reports.length === 0 && (
        <div className="py-20 flex flex-col items-center justify-center text-center space-y-4">
          <div className="p-5 bg-slate-50 rounded-full">
            <Box className="w-10 h-10 text-slate-300" />
          </div>
          <div>
            <p className="font-bold text-slate-800">No machines found</p>
            <p className="text-sm text-slate-400 uppercase tracking-widest font-black mt-1">Please add machines to generate reports</p>
          </div>
        </div>
      )}
    </motion.div>
  );
}

function ShiftSummary({ shift, log, icon: Icon, color }: { 
  shift: 'DAY' | 'NIGHT', 
  log?: ProductionRecord, 
  icon: any, 
  color: string 
}) {
  if (!log) {
    return (
      <div className="bg-slate-50/50 rounded-2xl p-3 border border-slate-100 flex items-center justify-between opacity-50 grayscale italic">
        <div className="flex items-center gap-2">
          <Icon className="w-3.5 h-3.5 text-slate-300" />
          <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{shift}</span>
        </div>
        <span className="text-[10px] font-bold text-slate-300 uppercase">No Entry</span>
      </div>
    );
  }

  return (
    <div className={cn(
      "rounded-2xl p-3 border transition-all",
      shift === 'DAY' ? "bg-amber-50/30 border-amber-100/50" : "bg-slate-50 border-slate-200"
    )}>
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <Icon className={cn("w-3.5 h-3.5", shift === 'DAY' ? "text-amber-500" : "text-slate-600")} />
          <span className={cn("text-[10px] font-black uppercase tracking-widest", shift === 'DAY' ? "text-amber-700" : "text-slate-900")}>
            {shift}
          </span>
        </div>
        <div className="flex items-center gap-1 opacity-60">
          <User className="w-2.5 h-2.5" />
          <span className="text-[9px] font-black uppercase">{log.operatorName}</span>
        </div>
      </div>
      
      <div className="flex flex-col gap-1">
        <p className="text-[10px] font-black text-slate-800 uppercase truncate">{log.designName}</p>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1">
            <Activity className="w-2.5 h-2.5 text-indigo-500" />
            <span className="text-[10px] font-bold text-slate-700">{log.totalStitches.toLocaleString()}</span>
          </div>
          <div className="flex items-center gap-1">
            <Ruler className="w-2.5 h-2.5 text-emerald-500" />
            <span className="text-[10px] font-bold text-slate-700">{log.totalMeters}m</span>
          </div>
        </div>
      </div>
    </div>
  );
}
